const movieExampleData = [
    {
        Title: "Back to the Future",
        Year: "1985",
        Rated: "PG",
        Released: "03 Jul 1985",
        Runtime: "116 min",
        Genre: "Adventure, Comedy, Sci-Fi",
        Director: "Robert Zemeckis",
        Writer: "Robert Zemeckis, Bob Gale",
        Actors: "Michael J. Fox, Christopher Lloyd, Lea Thompson",
        Plot: "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
        Language: "English",
        Country: "United States",
        Awards: "Won 1 Oscar. 23 wins & 25 nominations total",
        Poster: "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        Ratings: [
            { Source: "Internet Movie Database", Value: "8.5/10" },
            { Source: "Rotten Tomatoes", Value: "97%" },
            { Source: "Metacritic", Value: "87/100" },
        ],
        Metascore: "87",
        imdbRating: "8.5",
        imdbVotes: "1,239,275",
        imdbID: "tt0088763",
        Type: "movie",
        DVD: "17 Aug 2010",
        BoxOffice: "$212,836,762",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
    },
    {
        Title: "Top Gun: Maverick",
        Year: "2022",
        Rated: "PG-13",
        Released: "27 May 2022",
        Runtime: "130 min",
        Genre: "Action, Drama",
        Director: "Joseph Kosinski",
        Writer: "Jim Cash, Jack Epps Jr., Peter Craig",
        Actors: "Tom Cruise, Jennifer Connelly, Miles Teller",
        Plot: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to ...",
        Language: "English",
        Country: "United States",
        Awards: "Won 1 Oscar. 93 wins & 214 nominations total",
        Poster: "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
        Ratings: [
            { Source: "Internet Movie Database", Value: "8.3/10" },
            { Source: "Rotten Tomatoes", Value: "96%" },
            { Source: "Metacritic", Value: "78/100" },
        ],
        Metascore: "78",
        imdbRating: "8.3",
        imdbVotes: "590,794",
        imdbID: "tt1745960",
        Type: "movie",
        DVD: "22 Aug 2022",
        BoxOffice: "$718,732,821",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
    },
    {
        Title: "Pulp Fiction",
        Year: "1994",
        Rated: "R",
        Released: "14 Oct 1994",
        Runtime: "154 min",
        Genre: "Crime, Drama",
        Director: "Quentin Tarantino",
        Writer: "Quentin Tarantino, Roger Avary",
        Actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
        Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        Language: "English, Spanish, French",
        Country: "United States",
        Awards: "Won 1 Oscar. 70 wins & 75 nominations total",
        Poster: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Ratings: [
            { Source: "Internet Movie Database", Value: "8.9/10" },
            { Source: "Rotten Tomatoes", Value: "92%" },
            { Source: "Metacritic", Value: "95/100" },
        ],
        Metascore: "95",
        imdbRating: "8.9",
        imdbVotes: "2,110,312",
        imdbID: "tt0110912",
        Type: "movie",
        DVD: "20 Aug 2002",
        BoxOffice: "$107,928,762",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
    },
];

export { movieExampleData };
